# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'faker', '~> 1.9' and 
gem 'byebug', '~> 11.1.1' and
gem 'ruby2d', '~> 0.9.5' and
gem 'minitest', '~> 5'
